name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release'
        required: true
      development_version:
        description: 'Next snapshot version'
        required: true

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Create custom settings.xml 
        run: |
            mkdir -p ~/.m2
            cat <<EOF > ~/.m2/settings.xml
            <settings>
              <servers>
                <server>
                  <id>central</id>
                  <username>${CPP_USERNAME}</username>
                  <password>${CPP_PASSWORD}</password>
                </server>
              </servers>
            </settings>
            EOF
        env:
          CPP_USERNAME: ${{ secrets.CPP_USERNAME }}
          CPP_PASSWORD: ${{ secrets.CPP_PASSWORD }}     

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode > private.key
          gpg --batch --import private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure Git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Release prepare & perform with Maven
        run: |
          ./mvnw release:prepare release:perform -B \
            -Prelease \
            -DignoreSnapshots=true -DremoteTagging=false \
            -DreleaseVersion=${{ github.event.inputs.release_version }} \
            -DdevelopmentVersion=${{ github.event.inputs.development_version }}-SNAPSHOT \
            -Darguments="-DskipTests"
        env:
          GPG_TTY: $(tty)
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}            

      # - name: Update version to release
      #   run: ./mvnw versions:set -DnewVersion=${{ github.event.inputs.release_version }} && ./mvnw versions:commit

      # - name: Deploy to GitHub Packages
      #   run: ./mvnw deploy -DskipTests
      #   env:
      #     GPG_TTY: $(tty)
      #     GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: Release v${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Update version to next snapshot
      #   run: ./mvnw versions:set -DnewVersion=${{ github.event.inputs.next_snapshot }} && ./mvnw versions:commit

      # - name: Push updated pom.xml
      #   run: |
      #     git config --global user.name 'GitHub Actions'
      #     git config --global user.email 'github-actions@github.com'
      #     git add pom.xml
      #     git commit -m "Bump version to ${{ github.event.inputs.next_snapshot }}"
      #     git push
