name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release'
        required: true
      next_snapshot:
        description: 'Next snapshot version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Update version to release
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.release_version }} && mvn versions:commit

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v4
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          release_name: Release v${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: success()
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u USERNAME --password-stdin
          docker build -t ghcr.io/USERNAME/PROJECT_NAME:${{ github.event.inputs.release_version }} .
          docker push ghcr.io/USERNAME/PROJECT_NAME:${{ github.event.inputs.release_version }}

      - name: Update version to next snapshot
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.next_snapshot }} && mvn versions:commit

      - name: Push updated pom.xml
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add pom.xml
          git commit -m "Bump version to ${{ github.event.inputs.next_snapshot }}"
          git push