name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release'
        required: true
      next_snapshot:
        description: 'Next snapshot version'
        required: true

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
#          cache: 'maven'
#          server-id: github
#          settings-path: ${{ github.workspace }}
      - name: Create custom settings.xml 
        run: |
            mkdir -p ~/.m2
            cat <<EOF > ~/.m2/settings.xml
            <settings>
              <servers>
                <server>
                  <id>github-eximeebpms</id>
                  <username>${GITHUB_ACTOR}</username>
                  <password>${GITHUB_TOKEN}</password>
                </server>
                <server>
                  <id>github-release</id>
                  <username>${GITHUB_ACTOR}</username>
                  <password>${GITHUB_TOKEN}</password>
                </server>
              </servers>
            </settings>
            EOF
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

      # - name: Configure GitHub Packages
      #   run: |
      #     mkdir -p ~/.m2
      #     echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
      #     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      #     xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
      #     http://maven.apache.org/xsd/settings-1.0.0.xsd">
      #       <servers>
      #         <server>
      #           <id>github</id>
      #           <username>${{ github.actor }}</username>
      #           <password>${{ secrets.GITHUB_TOKEN }}</password>
      #         </server>
      #       </servers>
      #     </settings>' > ~/.m2/settings.xml



      - name: Update version to release
        run: ./mvnw versions:set -DnewVersion=${{ github.event.inputs.release_version }} && ./mvnw versions:commit

      - name: Deploy to GitHub Packages
        run: ./mvnw deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.release_version }}
          name: Release v${{ github.event.inputs.release_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version to next snapshot
        run: ./mvnw versions:set -DnewVersion=${{ github.event.inputs.next_snapshot }} && mvn versions:commit

      - name: Push updated pom.xml
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add pom.xml
          git commit -m "Bump version to ${{ github.event.inputs.next_snapshot }}"
          git push
